# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawdstacc < Formula
  desc "Self-hosted Codespaces for Claude Code, on your own Mac"
  homepage "https://github.com/larskghf/clawdstacc"
  version "0.2.1"
  license "MIT"

  depends_on "code-server"
  depends_on "tmux"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/larskghf/clawdstacc/releases/download/v0.2.1/clawdstacc_0.2.1_darwin_amd64.tar.gz"
    sha256 "0afd9d8a7c7b50dac563cd2c3e5069f7bebd9c95697f8ea97ba334e39b57de84"

    define_method(:install) do
      bin.install "bin/clawdstacc"
      # Stash the conf example under HOMEBREW_PREFIX/etc/clawdstacc/ so users
      # can copy it without hunting for the source tarball later.
      (etc/"clawdstacc").install "clawdstacc.conf.example"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/larskghf/clawdstacc/releases/download/v0.2.1/clawdstacc_0.2.1_darwin_arm64.tar.gz"
    sha256 "5b8e499bf44c44b3d90a83e49c67df708be57fc7b1e737584d1153d7388b9467"

    define_method(:install) do
      bin.install "bin/clawdstacc"
      # Stash the conf example under HOMEBREW_PREFIX/etc/clawdstacc/ so users
      # can copy it without hunting for the source tarball later.
      (etc/"clawdstacc").install "clawdstacc.conf.example"
    end
  end

  def post_install
    # On `brew upgrade`, re-render plists, restart only the agents whose
    # plist content actually changed, and kickstart the dashboard so its
    # in-memory templates pick up the new binary. No-op on fresh installs
    # (reload exits cleanly when no clawdstacc agents are installed yet).
    system "#{bin}/clawdstacc", "reload" rescue nil
  end

  def caveats
    <<~EOS
      clawdstacc also needs the Claude Code CLI (not on brew):
        curl -fsSL https://claude.com/install.sh | bash

      First-time setup — the first `clawdstacc setup` writes
      ~/.config/clawdstacc/clawdstacc.conf from the bundled defaults and
      exits. Review it, then re-run:
        clawdstacc setup
        $EDITOR ~/.config/clawdstacc/clawdstacc.conf
        clawdstacc setup
    EOS
  end

  test do
    assert_match "clawdstacc", shell_output("#{bin}/clawdstacc version")
  end
end
