# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawdstacc < Formula
  desc "Self-hosted Codespaces for Claude Code, on your own Mac"
  homepage "https://github.com/larskghf/clawdstacc"
  version "0.3.2"
  license "MIT"

  depends_on "code-server"
  depends_on "tmux"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/larskghf/clawdstacc/releases/download/v0.3.2/clawdstacc_0.3.2_darwin_amd64.tar.gz"
    sha256 "133c276d10c7bee4b9ae501e5660942faf219f02b07cf99b8b8227cb6403fb65"

    define_method(:install) do
      bin.install "bin/clawdstacc"
      # Stash the conf example under HOMEBREW_PREFIX/etc/clawdstacc/ so users
      # can copy it without hunting for the source tarball later.
      (etc/"clawdstacc").install "clawdstacc.conf.example"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/larskghf/clawdstacc/releases/download/v0.3.2/clawdstacc_0.3.2_darwin_arm64.tar.gz"
    sha256 "fd96b4959106dd14c9ea6a56b47dd2c598177ce6bee03c532b313b47ced5c4e8"

    define_method(:install) do
      bin.install "bin/clawdstacc"
      # Stash the conf example under HOMEBREW_PREFIX/etc/clawdstacc/ so users
      # can copy it without hunting for the source tarball later.
      (etc/"clawdstacc").install "clawdstacc.conf.example"
    end
  end

  def post_install
    # On `brew upgrade`, re-render plists, restart only the agents whose
    # plist content actually changed, and kickstart the dashboard so its
    # in-memory templates pick up the new binary. No-op on fresh installs
    # (reload exits cleanly when no clawdstacc agents are installed yet).
    system "#{bin}/clawdstacc", "reload" rescue nil
  end

  def caveats
    <<~EOS
      clawdstacc also needs the Claude Code CLI (not on brew):
        curl -fsSL https://claude.com/install.sh | bash

      First-time setup — the first `clawdstacc setup` writes
      ~/.config/clawdstacc/clawdstacc.conf from the bundled defaults and
      exits. Review it, then re-run:
        clawdstacc setup
        $EDITOR ~/.config/clawdstacc/clawdstacc.conf
        clawdstacc setup
    EOS
  end

  test do
    assert_match "clawdstacc", shell_output("#{bin}/clawdstacc version")
  end
end
