# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawdstacc < Formula
  desc "Self-hosted Codespaces for Claude Code, on your own Mac"
  homepage "https://github.com/larskghf/clawdstacc"
  version "0.3.3"
  license "MIT"

  depends_on "code-server"
  depends_on "tmux"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/larskghf/clawdstacc/releases/download/v0.3.3/clawdstacc_0.3.3_darwin_amd64.tar.gz"
    sha256 "a8d2840ca43d1dc7a03bdd81058bb8947618d9737624de7d5aadfe0e9e5011c7"

    define_method(:install) do
      bin.install "bin/clawdstacc"
      # Stash the conf example under HOMEBREW_PREFIX/etc/clawdstacc/ so users
      # can copy it without hunting for the source tarball later.
      (etc/"clawdstacc").install "clawdstacc.conf.example"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/larskghf/clawdstacc/releases/download/v0.3.3/clawdstacc_0.3.3_darwin_arm64.tar.gz"
    sha256 "e8b6dd8fc2c4c664a14a63848a03c6559b93a5bc39afcccab7bdd930824d153b"

    define_method(:install) do
      bin.install "bin/clawdstacc"
      # Stash the conf example under HOMEBREW_PREFIX/etc/clawdstacc/ so users
      # can copy it without hunting for the source tarball later.
      (etc/"clawdstacc").install "clawdstacc.conf.example"
    end
  end

  def post_install
    # On `brew upgrade`, re-render plists, restart only the agents whose
    # plist content actually changed, and kickstart the dashboard so its
    # in-memory templates pick up the new binary. No-op on fresh installs
    # (reload exits cleanly when no clawdstacc agents are installed yet).
    system "#{bin}/clawdstacc", "reload" rescue nil
  end

  def caveats
    <<~EOS
      clawdstacc also needs the Claude Code CLI (not on brew):
        curl -fsSL https://claude.com/install.sh | bash

      First-time setup — the first `clawdstacc setup` writes
      ~/.config/clawdstacc/clawdstacc.conf from the bundled defaults and
      exits. Review it, then re-run:
        clawdstacc setup
        $EDITOR ~/.config/clawdstacc/clawdstacc.conf
        clawdstacc setup
    EOS
  end

  test do
    assert_match "clawdstacc", shell_output("#{bin}/clawdstacc version")
  end
end
